services:
  idu:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    env_file:
      - .env
    container_name: idu
    hostname: idu
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    command: ["sh", "-c", "python3 -m uvicorn src.main:app --host 0.0.0.0 --port 8000"]
    stop_grace_period: 30s
