name: "Test App"

run-name: "Branch name: ${{ github.ref_name }} / Test App"
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Check code format
        run: |
          uv run ruff check .

      - name: Run unit tests
        run: |
          uv run pytest tests/unit

